id: P39B5079F
initial_creation_type: input
source_metadata:
  title: Longchen Rabjam Series
  language: bo
  description: 'Texts by and about Longchen Rabjam (klong chen rab ''byams, 1308-1364),
    also known as Drimé Özer (dri med ''od zer), who is widely acknowledged as the
    greatest exponent of Dzogpachenpo, or the Great Perfection, in Tibetan history:'
  volume:
    67fe3fc477284416a13efdfef0bd2122:
      title: 'A Mirror Revealing the Crucial Points: Advice on the Ultimate Meaning'
      parent: Advice
    d37df6f89d3a4cc29ad4770f9ab5f69d:
      title: 'A Wish-Fulfilling Gem: Guidance on the Meaning of Being at Ease with
        Illusion, A Dzogchen Teaching'
      parent: Advice
    4f74d69469994e0dae01c2f036d4c7a9:
      title: 'Crucial Advice: A Complete Set of Instructions for the Bardos'
      parent: Advice
    533f5ee9ce8a45f4913b528c80fd7adb:
      title: Song of the Enchanting Wildwoods
      parent: Advice
    38c0eecb74e1453eadd8b83de4afef5e:
      title: Thirty Pieces of Heart Advice
      parent: Advice
    384b609134494e41bef68fefe04e4665:
      title: 'From ''Finding Comfort and Ease in Meditation'': A Guide to Locations
        for Cultivating Samadhi'
      parent: Meditation
    937f9adda2b346eab06b712815069dfc:
      title: 'From ''Finding Comfort and Ease in Meditation'': The Practitioner of
        Meditation'
      parent: Meditation
    802ac8f940484cac948994a5269723e3:
      title: The Prayer that Swiftly Fulfils All Wishes (Sampa Nyur Drupma)
      parent: Guru Rinpoche Prayers
    b4ef8e1805ee438a93b1a5bd978cd412:
      title: Guru Yoga of the Great Omniscient One, Longchenpa
      parent: Guru Yoga
    aba436fa1f3449fe8dd333f82a10254a:
      title: 'Rain of Wisdom, Love and Spiritual Power: A Guru Yoga of the Three Mañjughoṣas
        of the Land of Snow'
      parent: Guru Yoga
    e9d1e42db914492eb17eb2ef3b527dff:
      title: Prayer to Longchenpa (Adapted from the Words of Mipham Rinpoche)
      parent: Lineage Prayers
    bfb6573e6e4149aa96835357f2a9896f:
      title: Prayer to the Omniscient Longchen Rabjam
      parent: Lineage Prayers
    92b770907e7544a4b3ee9a2c6827bfb7:
      title: In Praise of Longchenpa – The Greatness of the Omniscient Longchen Rabjam
      parent: Praise
    527e7333e33d4464aceb79f7f439157a:
      title: Dedication (Sangye tenpa...)
      parent: Prayers
    1f37bdabacc8498781ab2e08ae77d461:
      title: Food Offering Prayer
      parent: Prayers
    3e654cfaed8c460f8f58a8c427e44c10:
      title: 'Gyang Lu: A Song of Calling from Afar'
      parent: Prayers
    321e011a7a914fadbadcc8493a34df27:
      title: 'The Pure Three Kāyas Ablaze in Perfect Splendour: A Prayer Based on
        the Meaning of the Great Perfection'
      parent: Prayers
    d0699c34460e4f0d89c07cb9aa3aeae9:
      title: Prayer and Call from Afar to the Great Omniscient One
      parent: Calling the Guru from Afar
    2b07c3b4ed7f4ba2911ae1ac6b67640f:
      title: The Song of the Vajra
      parent: Songs
created_at: '2022-03-01T00:41:21.605479'
last_modified_at: '2022-03-01T00:41:21.605483'
